### ISSUE TITLE
Feature_setting

### ISSUE THREAD

**Issue by BSS0331** [BSS0331/Capstone-III#19]

**Comment by BSS0331** [comment]
FAB 모듈 생성완료
**Todo List**
- [ ] 로그인
- [ ] 회원가입
- [ ] 소셜 로그인 및 회원가입
- [ ] 닉네임 설정 및 변경
- [ ] 비밀번호 변경
- [x] 모듈 화면에서 Tab Bar 숨기기 (추가)
